config/routes.rb
SampleApp1::Application.routes.draw do
  get "monitor_panel/show"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/checkLocation', to: 'static_pages#checkLocation'

  resources :posts do
    collection do
      get 'checkLocation'
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :audio, :comment, :location, :latitude, :longitude ,:user_id, :video
  belongs_to :user
  validates :user_id, :location, presence: true
  validates :comment, presence: true, length: {maximum: 140}
  default_scope order: 'posts.created_at DESC'

  validates :latitude, :presence => {message: "Not a valid location on Google Maps, please check city field" }
  geocoded_by :location
  before_validation :geocode
  after_validation :geocode, :if => :location_changed?
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :signed_in_user , only: [:create, :destroy]
  before_filter :correct_user,   only: :destroy

  def create
    @post = current_user.posts.build(params[:post])
    @searchResult = Geocoder.search(@post.location)
    if @searchResult[0] == nil
       #TODO
       @post.save
    else
      if @post.save
        flash[:success] = "Post created!"
      else
      end

      @post.location = @searchResult[0].address
    end

  end

  def destroy
    @post.destroy
    redirect_to root_url

  end

  def checkLocation
    puts "----checkLocation-----------------------------"
  end



  private

    def correct_user
      @post = current_user.posts.find_by_id(params[:id])
      redirect_to root_url if @post.nil?
    end


end

app/helpers/posts_helper.rb
module PostsHelper
  def drawAPost(post,searchResult)

    if (searchResult[0].latitude > 0 )
      northSouth = "N"
    else
      northSouth = "S"
    end

    if (searchResult[0].longitude > 0 )
      eastWest = "E"
    else
      eastWest = "W"
    end
    ll = searchResult[0].latitude.to_s() + " " + northSouth + " " + searchResult[0].longitude.to_s()  + " " + eastWest
    # parse video:check if not empty, then add https:
    youtubeVideo=""
    if post.video.empty?
    else
      youtubeVideo = "\<embed width='200' height='200' src='https:#{post.video}?autoplay=1' hidden='false' autoplay='ture'></embed>"
    end
    # parse audio
    audio=""
    if post.audio.empty?
    else
      audio = "\<audio controls='' autoplay='' style='display:none'><source src='#{post.audio}' type='audio/mpeg'></audio>"
    end
    postPoint = {}
    postPoint["#{post.location}"]={"ll"=> ll ,
                                    "country"=> "" ,
                                    "audio"=> audio ,
                                    "name"=> post.user.name ,
                                    "video"=> youtubeVideo ,
                                    "comment"=> post.comment,
                                    "like"=> "" ,
                                    "dislike"=> ""  }


  end

end

app/views/posts/_post.html.erb
<li xmlns="http://www.w3.org/1999/html">
  <span class="location">Post Location: <%= post.location %></span></br>
  <% if !post.audio.empty? %>
  <span class="audio">Audio: <%= post.audio %></span></br>
  <% end  %>
  <% if !post.video.empty? %>
  <span class="video">Video: <%= post.video %></span></br>
  <% end  %>
  <span class="comment">Comment: <%= post.comment %></span>

  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
  <% if current_user?(post.user) %>
      <%= link_to "edit", edit_post_path, method: :post%>
      <%= link_to "delete", post, method: :delete,
                  data: { confirm: "You sure?" },
                  title: post.comment %>
  <% end %>
</li>

app/views/posts/create.js.erb
<% if @post.errors.any? %>
console.log('Error');
$('#postForm').modal('hide')
$('#postForm').replaceWith("<%=escape_javascript(render "shared/post_form") %>")
$('#postForm').modal('show')
<% else %>
console.log('Created');
$('#postForm').modal('hide')
//draw the new
//TODO
location.reload();

<% end %>